/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginSoroviDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginJavobiDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operatorlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hisobot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    dan?: string;
                    gacha?: string;
                    operatorId?: number;
                    guruh?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HisobotDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boshqaruv/bugun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BoshqaruvBugunDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    dan?: string;
                    gacha?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditYozuviDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/eksport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuditEksportDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/zaxira": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ZaxiraJavobiDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foydalanuvchilar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FoydalanuvchiYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foydalanuvchilar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FoydalanuvchiTahrirlashDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foydalanuvchilar/{id}/ruxsatlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RuxsatlarOrnatishDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FoydalanuvchiDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foydalanuvchilar/{id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PinOrnatishDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yoqilgilar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["YoqilgiTuriDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["YoqilgiYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["YoqilgiTuriDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yoqilgilar/narx-tarixi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NarxTarixiDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yoqilgilar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["YoqilgiTahrirlashDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["YoqilgiTuriDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aparatlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AparatDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AparatYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AparatDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aparatlar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AparatTahrirlashDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AparatDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    dan?: string;
                    gacha?: string;
                    operatorId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaTafsilotDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/joriy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaDto"];
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/och": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/smenalar/{id}/yop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SmenaYopishDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SmenaDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sotuvlar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    dan?: string;
                    gacha?: string;
                    operatorId?: number;
                    smenaId?: number;
                    holati?: components["schemas"]["SotuvHolati"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SotuvDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SotuvYaratishDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SotuvDto"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SotuvDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sotuvlar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SotuvTahrirlashDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SotuvDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sotuvlar/{id}/bekor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SotuvBekorQilishDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SotuvDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operatorlar/{id}/hisob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    oy?: string;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OperatorHisobDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operatorlar/{id}/harakat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HarakatYaratishDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HisobHarakatiDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AparatDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            raqam: number;
            /** Format: int32 */
            yoqilgiTuriId: number;
            yoqilgiNomi: string;
            /** Format: double */
            totalLitr: number;
        };
        AparatTahrirlashDto: {
            /** Format: int32 */
            raqam: number;
            /** Format: int32 */
            yoqilgiTuriId: number;
            /** Format: double */
            totalLitr?: null | number;
        };
        AparatYaratishDto: {
            /** Format: int32 */
            raqam: number;
            /** Format: int32 */
            yoqilgiTuriId: number;
            /** Format: double */
            boshlangichTotalLitr: number;
        };
        AuditEksportDto: {
            turi: string;
            tafsilot: string;
        };
        AuditYozuviDto: {
            /** Format: int32 */
            id: number;
            /** Format: date-time */
            vaqt: string;
            kim: string;
            amal: string;
            tafsilot: string;
        };
        BoshqaruvBugunDto: {
            kpi: components["schemas"]["BoshqaruvKpiDto"];
            tolovUlushlari: components["schemas"]["TolovUlushiDto"][];
            yoqilgiUlushlari: components["schemas"]["YoqilgiUlushiDto"][];
            oxirgiKunlar: components["schemas"]["KunlikDto"][];
            operatorlar: components["schemas"]["OperatorQisqaDto"][];
            oxirgiSotuvlar: components["schemas"]["SotuvDto"][];
        };
        BoshqaruvKpiDto: {
            /** Format: int64 */
            bugungiSumma: number;
            /** Format: double */
            bugungiLitr: number;
            /** Format: int32 */
            sotuvSoni: number;
            /** Format: int32 */
            ochiqSmenalar: number;
            /** Format: int64 */
            kechagiSumma: number;
            /** Format: int64 */
            oyJami: number;
            /** Format: int64 */
            oyKamomat: number;
        };
        FoydalanuvchiDto: {
            /** Format: int32 */
            id: number;
            toliqIsm: string;
            login: string;
            rol: components["schemas"]["Rol"];
            faol: boolean;
            /** Format: int64 */
            oylikMaosh: number;
            ruxsatlar: components["schemas"]["Ruxsat"][];
        };
        FoydalanuvchiTahrirlashDto: {
            toliqIsm: string;
            rol: components["schemas"]["Rol"];
            faol: boolean;
            /** Format: int64 */
            oylikMaosh: number;
            login?: null | string;
        };
        FoydalanuvchiYaratishDto: {
            toliqIsm: string;
            login: string;
            rol: components["schemas"]["Rol"];
            /** Format: int64 */
            oylikMaosh: number;
            parolYokiPin: string;
        };
        /** @enum {unknown} */
        HarakatTuri: "Maosh" | "Avans" | "Kamomat" | "Ortiqcha" | "Tolov";
        HarakatYaratishDto: {
            turi: components["schemas"]["HarakatTuri"];
            /** Format: int64 */
            summa: number;
            izoh: string;
        };
        HisobHarakatiDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            operatorId: number;
            /** Format: date-time */
            sana: string;
            turi: components["schemas"]["HarakatTuri"];
            /** Format: int64 */
            summa: number;
            izoh: string;
            kimYozdi: string;
        };
        HisobotDto: {
            qatorlar: components["schemas"]["HisobotQatoriDto"][];
            jami: components["schemas"]["HisobotQatoriDto"];
        };
        HisobotQatoriDto: {
            guruh: string;
            yoqilgi: null | string;
            /** Format: double */
            litr: number;
            /** Format: int64 */
            summa: number;
            /** Format: int64 */
            naqd: number;
            /** Format: int64 */
            plastik: number;
            /** Format: int64 */
            click: number;
            /** Format: int32 */
            soni: number;
            /** Format: int64 */
            kamomat: number;
            /** Format: int64 */
            avans: number;
            /** Format: int32 */
            bekorSoni: number;
            jami: boolean;
        };
        KunlikDto: {
            /** Format: date */
            sana: string;
            /** Format: int64 */
            summa: number;
            /** Format: double */
            litr: number;
        };
        LoginJavobiDto: {
            token: string;
            /** Format: date-time */
            tokenMuddati: string;
            foydalanuvchi: components["schemas"]["FoydalanuvchiDto"];
        };
        LoginSoroviDto: {
            login: string;
            parolYokiPin: string;
        };
        NarxTarixiDto: {
            /** Format: date-time */
            vaqt: string;
            yoqilgi: string;
            /** Format: int64 */
            eskiNarx: number;
            /** Format: int64 */
            yangiNarx: number;
            kim: string;
        };
        OperatorHisobDto: {
            /** Format: int32 */
            operatorId: number;
            operatorIsmi: string;
            /** Format: int64 */
            oylikMaosh: number;
            /** Format: int64 */
            oyJami: number;
            /** Format: int64 */
            qoldiq: number;
            /** Format: int64 */
            oySavdo: number;
            /** Format: int32 */
            oySmenalar: number;
            harakatlar: components["schemas"]["HisobHarakatiDto"][];
        };
        OperatorQisqaDto: {
            /** Format: int32 */
            operatorId: number;
            ism: string;
            /** Format: int64 */
            bugungiSumma: number;
            /** Format: double */
            bugungiLitr: number;
            /** Format: int32 */
            sotuvSoni: number;
            smenaOchiqmi: boolean;
        };
        PinOrnatishDto: {
            yangiParolYokiPin: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        /** @enum {unknown} */
        Rol: "Operator" | "Boshliq" | "Admin";
        /** @enum {unknown} */
        Ruxsat: "Boshqaruv" | "SotuvKiritish" | "SmenaOchish" | "SmenaYopish" | "Smenalar" | "Hisobotlar" | "Eksport" | "Operatorlar" | "AvansBerish" | "SotuvBekorQilish" | "SotuvTahrirlash" | "Audit" | "Sozlamalar";
        RuxsatlarOrnatishDto: {
            ruxsatlar: components["schemas"]["Ruxsat"][];
        };
        SmenaDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            operatorId: number;
            operatorIsmi: string;
            /** Format: date-time */
            boshlandi: string;
            /** Format: date-time */
            tugadi: null | string;
            /** Format: int64 */
            kutilganNaqd: number;
            /** Format: int64 */
            kutilganPlastik: number;
            /** Format: int64 */
            kutilganClick: number;
            /** Format: double */
            jamiLitr: number;
            /** Format: int32 */
            sotuvSoni: number;
            /** Format: int64 */
            topshirilganNaqd: null | number;
            /** Format: int64 */
            topshirilganPlastik: null | number;
            /** Format: int64 */
            topshirilganClick: null | number;
            /** Format: int64 */
            farq: number;
            /** Format: int64 */
            kamomat: number;
            /** Format: int64 */
            ortiqcha: number;
            izoh: null | string;
        };
        SmenaTafsilotDto: {
            smena: components["schemas"]["SmenaDto"];
            sotuvlar: components["schemas"]["SotuvDto"][];
        };
        SmenaYopishDto: {
            /** Format: int64 */
            naqd: number;
            /** Format: int64 */
            plastik: number;
            /** Format: int64 */
            click: number;
            izoh: null | string;
        };
        SotuvBekorQilishDto: {
            sabab: string;
        };
        SotuvDto: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            smenaId: number;
            /** Format: int32 */
            operatorId: number;
            operatorIsmi: string;
            /** Format: int32 */
            aparatId: number;
            /** Format: int32 */
            aparatRaqami: number;
            yoqilgiNomi: string;
            /** Format: int64 */
            narx: number;
            /** Format: double */
            litr: number;
            /** Format: int64 */
            summa: number;
            /** Format: date-time */
            vaqt: string;
            tolovlar: components["schemas"]["TolovDto"][];
            holati: components["schemas"]["SotuvHolati"];
            bekorSababi: null | string;
            bekorQilgan: null | string;
        };
        /** @enum {unknown} */
        SotuvHolati: "Faol" | "BekorQilingan";
        SotuvTahrirlashDto: {
            /** Format: int32 */
            aparatId: number;
            /** Format: int64 */
            summa: number;
            tolovlar: components["schemas"]["TolovDto"][];
            sabab: string;
        };
        SotuvYaratishDto: {
            /** Format: int32 */
            aparatId: number;
            /** Format: double */
            litr: null | number;
            /** Format: int64 */
            summa: null | number;
            tolovlar: null | components["schemas"]["TolovDto"][];
            /** Format: uuid */
            idempotencyKey: string;
            tolovTuri?: null | components["schemas"]["TolovTuri"];
        };
        TolovDto: {
            turi: components["schemas"]["TolovTuri"];
            /** Format: int64 */
            summa: number;
        };
        /** @enum {unknown} */
        TolovTuri: "Naqd" | "Plastik" | "Click";
        TolovUlushiDto: {
            turi: components["schemas"]["TolovTuri"];
            /** Format: int64 */
            summa: number;
        };
        YoqilgiTahrirlashDto: {
            nomi: string;
            /** Format: int64 */
            narx: number;
            rang: string;
        };
        YoqilgiTuriDto: {
            /** Format: int32 */
            id: number;
            nomi: string;
            /** Format: int64 */
            narx: number;
            rang: string;
            aparatgaBiriktirilgan: boolean;
        };
        YoqilgiUlushiDto: {
            nomi: string;
            rang: string;
            /** Format: double */
            litr: number;
            /** Format: int64 */
            summa: number;
        };
        YoqilgiYaratishDto: {
            nomi: string;
            /** Format: int64 */
            narx: number;
            rang: string;
        };
        ZaxiraJavobiDto: {
            faylNomi: string;
            /** Format: int64 */
            hajmBayt: number;
            /** Format: date-time */
            vaqt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
