// <auto-generated />
using System;
using FuelControl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelControl.Api.Data.Migrations
{
    [DbContext(typeof(FuelControlDbContext))]
    [Migration("20261002044903_Boshlangich")]
    partial class Boshlangich
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FuelControl.Core.Modellar.Aparat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Raqam")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalLitr")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("YoqilgiTuriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Raqam")
                        .IsUnique();

                    b.HasIndex("YoqilgiTuriId");

                    b.ToTable("Aparatlar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.AuditYozuvi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tafsilot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Vaqt");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Foydalanuvchi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BlokGacha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Faol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OylikMaosh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParolXeshi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruxsatlar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToliqIsm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("XatoUrinishlar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Foydalanuvchilar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.HisobHarakati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Izoh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KimYozdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("TEXT");

                    b.Property<long>("Summa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId", "Sana");

                    b.ToTable("Harakatlar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.NarxTarixi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EskiNarx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.Property<long>("YangiNarx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YoqilgiNomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YoqilgiTuriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Vaqt");

                    b.ToTable("NarxTarixlari");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Smena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Boshlandi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Izoh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("JamiLitr")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("KutilganClick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KutilganNaqd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KutilganPlastik")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SotuvSoni")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TopshirilganClick")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TopshirilganNaqd")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TopshirilganPlastik")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Tugadi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Boshlandi");

                    b.HasIndex("OperatorId", "Tugadi");

                    b.ToTable("Smenalar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Sotuv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AparatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BekorQilgan")
                        .HasColumnType("TEXT");

                    b.Property<string>("BekorSababi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Holati")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Litr")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("Narx")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SmenaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Summa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Vaqt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AparatId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OperatorId");

                    b.HasIndex("SmenaId");

                    b.HasIndex("Vaqt");

                    b.ToTable("Sotuvlar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.SotuvTolovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SotuvId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Summa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SotuvId");

                    b.ToTable("SotuvTolovlari");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.YoqilgiTuri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Narx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nomi")
                        .IsUnique();

                    b.ToTable("Yoqilgilar");
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Aparat", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.YoqilgiTuri", null)
                        .WithMany()
                        .HasForeignKey("YoqilgiTuriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.HisobHarakati", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Foydalanuvchi", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Smena", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Foydalanuvchi", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Sotuv", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Aparat", null)
                        .WithMany()
                        .HasForeignKey("AparatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelControl.Core.Modellar.Foydalanuvchi", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FuelControl.Core.Modellar.Smena", null)
                        .WithMany()
                        .HasForeignKey("SmenaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.SotuvTolovi", b =>
                {
                    b.HasOne("FuelControl.Core.Modellar.Sotuv", null)
                        .WithMany("Tolovlar")
                        .HasForeignKey("SotuvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelControl.Core.Modellar.Sotuv", b =>
                {
                    b.Navigation("Tolovlar");
                });
#pragma warning restore 612, 618
        }
    }
}
